import gulp from 'gulp'
import { deleteSync } from 'del'
import fileinclude from 'gulp-file-include'
import htmlmin from 'gulp-htmlmin'
import * as dartSass from 'sass'
import gulpSass from 'gulp-sass'
import fs from 'fs'
import replace from 'gulp-replace'
import webpack from 'webpack-stream'
import through from 'through2'
import named from 'vinyl-named'
import sourcemaps from 'gulp-sourcemaps'

const sass = gulpSass(dartSass)
let packageJson
const mockFilesList = [
  {
    uploaded: '2023-10-01T00:00:00.000Z',
    checksums: {
      md5: '1234567890'
    },
    httpEtag: '"1234567890"',
    etag: '1234567890',
    size: 3273984,
    version: '1234567890',
    key: '1.jpg'
  }
]

const paths = {
  dev: {
    src: 'src/dev/**/*',
    dest: 'dist/'
  },
  html: {
    src: 'src/*.html',
    dest: 'dist/'
  },
  htmlinclude: 'src/include/*.html',
  cloudflareMeta: {
    src: 'src/_*',
    dest: 'dist/'
  },
  js: {
    src: 'src/js/app.js',
    dest: 'dist/js/'
  },
  scss: {
    src: 'src/scss/*.scss',
    dest: 'dist/css/'
  },
  ts: {
    src: 'src/ts/image.ts',
    dest: 'dist/ts/'
  }
}

// Get Package information from package.json
async function getPackageInfo() {
  packageJson = JSON.parse(fs.readFileSync('package.json'))
  return Promise.resolve()
}

// Wipe the dist directory
export async function clean() {
  return deleteSync(['dist/'])
}

// Minify HTML
async function html() {
  return gulp
    .src(paths.html.src)
    .pipe(fileinclude({ prefix: '@@', basepath: 'src/include/' }))
    .pipe(replace('{{commit-hash}}', process.env.CF_PAGES_COMMIT_SHA))
    .pipe(replace('{{branch-name}}', process.env.CF_PAGES_BRANCH))
    .pipe(replace('{{environment}}', process.env.CF_PAGES_BRANCH === 'main' ? 'production' : 'development'))
    .pipe(replace('{{sentry-dsn}}', process.env.SENTRY_DSN))
    .pipe(replace('{{package-name}}', packageJson.name))
    .pipe(replace('{{package-version}}', packageJson.version))
    .pipe(
      htmlmin({
        collapseBooleanAttributes: true,
        collapseWhitespace: true,
        includeAutoGeneratedTags: false,
        minifyURLs: true,
        removeAttributeQuotes: true,
        removeComments: true,
        removeEmptyAttributes: true,
        removeRedundantAttributes: true,
        removeScriptTypeAttributes: true,
        removeStyleLinkTypeAttributes: true
      })
    )
    .pipe(gulp.dest(paths.html.dest))
}

// Minify JavaScript
async function js() {
  return gulp
    .src(paths.js.src)
    .pipe(named())
    .pipe(
      webpack({
        devtool: 'source-map',
        mode: 'production',
        module: {
          rules: [
            {
              test: /\.ts$/,
              use: 'ts-loader'
            },
            {
              test: /\.js$/i,
              loader: 'string-replace-loader',
              options: {
                multiple: [
                  { search: '{{commit-hash}}', replace: process.env.CF_PAGES_COMMIT_SHA },
                  { search: '{{branch-name}}', replace: process.env.CF_PAGES_BRANCH },
                  {
                    search: '{{environment}}',
                    replace: process.env.CF_PAGES_BRANCH === 'main' ? 'production' : 'development'
                  },
                  { search: '{{sentry-dsn}}', replace: process.env.SENTRY_DSN },
                  { search: '{{package-name}}', replace: packageJson.name },
                  { search: '{{package-version}}', replace: packageJson.version }
                ]
              }
            }
          ]
        }
      })
    )
    .pipe(sourcemaps.init({ loadMaps: true }))
    .pipe(
      through.obj(function (file, enc, cba) {
        // Don't pipe through any source map files. They will be handled by gulp-sourcemaps.
        // Also filter out /functions/ files and *.d.ts files
        if (!/\.map$/.test(file.path) && !/functions/.test(file.path) && !/\.d\.ts$/.test(file.path)) {
          this.push(file)
        }

        cba()
      })
    )
    .pipe(sourcemaps.write('.', { addComment: false }))
    .pipe(gulp.dest(paths.js.dest))
}

// Compile SCSS
async function scss() {
  return gulp
    .src(paths.scss.src)
    .pipe(sass({ outputStyle: 'compressed' }))
    .pipe(gulp.dest(paths.scss.dest))
}

// Copy Cloudflare Pages Meta Info
async function cloudflareMeta() {
  return gulp.src(paths.cloudflareMeta.src).pipe(gulp.dest(paths.cloudflareMeta.dest))
}

// Copy files for local dev server
async function localDev() {
  return gulp.src(paths.dev.src).pipe(gulp.dest(paths.dev.dest))
}

// Watch for changes
function watchSrc() {
  console.warn('Watching for changes... Press [CTRL+C] to stop.')
  gulp.watch([paths.html.src, paths.htmlinclude], html)
  gulp.watch(paths.scss.src, scss)
  gulp.watch(paths.js.src, js)
}

export default gulp.series(getPackageInfo, cloudflareMeta, js, scss, html)

export const watch = gulp.series(getPackageInfo, localDev, watchSrc)
